### ISSUE TITLE
Introducción / Introduction

### ISSUE THREAD

**Issue by vgayolrs** [PH-espagnol/borradores#1]
@arojascastro , @mariajoafana 
¡Saludos! La idea de este repositorio aparte de PH es poder discutir en español los asuntos de traducción y demás del sitio en español sin interferir con el funcionamiento del sitio principal y las discusiones en inglés. Una vez que tengamos seguridad de que las traducciones funcionan bien (no solamente en cuanto al idioma, sino también en cuanto a los conceptos de informática y la escritura de código), los trasladaremos a PH. Además, nos sirve para entrenarnos en GitHub.

---

@acrymble, @ahegel, @amandavisconti, @fredgibbs, @ianmilligan1, @jerielizabeth, @tapar001, @wcaleb

Hi everybody! The Spanish team has set up this repository to discuss the drafts of lessons translations. The discussion here will be in Spanish to improve the work in a better way and to avoid confussion in the main PH repositories. Once tuned-up, we will move them to the PH-sumbissions repository. In addition, we'll use this one to train us in GitHub without interfering with the operation of the Programming Historian GitHub. You all have been invited to join us just to keep track of what are we doing and to locate the raw drafts of each lesson. All comments are wellcome.

**Comment by mariajoafana** [comment]
@vgayolrs @arojascastro excelente. Acabo de leer la wiki y me parece que está muy bien.

**Comment by mariajoafana** [comment]
Finalmente me llegó la invitación para poder subir archivos al Github, acabo de subir el de retroalimentación y sigo avanzando en la traducción del de Network analysis. 
Ya empiezan a llegar interesados en colaborar con PH después de mandar la encuesta, les ire contando.

**Comment by vgayolrs** [comment]
@mariajoafana : ya te vi inscrita en la organización de PH, pero también acepta la invitación para la organización PH-es (ésta), para que tengas completo acceso al trabajo de edición sobre los borradores de las lecciones en este repositorio: https://github.com/PH-espagnol/borradores
Saludos!
