### ISSUE TITLE
contar-palabras >> ensamblar todo

### ISSUE THREAD

**Issue by jairomelo** [PH-espagnol/borradores#10]
Para que funcione, después de todos los cambios, el programa tiene que quedar así:

``` python

import urllib2, obo

url = 'http://www.oldbaileyonline.org/browse.jsp?id=t17800628-33&div=t17800628-33'

respuesta = urllib2.urlopen(url)
html = respuesta.read()
texto = obo.quitarEtiquetas(html).lower()
listapalabcompl = obo.quitaNoAlfaNum(texto)
listapalabras = obo.removeStopwords(listapalabcompl, obo.stopwords)
diccionario = obo.listaPabafrecDicc(listapalabras)
orddiccionario = obo.ordPabaDicc(diccionario)

for s in orddiccionario: print(str(s))

```

**Comment by vgayolrs** [comment]
Genial @jairomelo . ¿Considerarías darle una revisada a código de todas las lecciones de Introducción a Python a partir del lunes 7.11? Yo creo que ya estarán corregidas para entonces y si das tu aprobación quedarían revisadas y listas para publicación.

¿Les parece @mariajoafana y @arojascastro ?

**Comment by mariajoafana** [comment]
Listo, me pongo a corregirlas cuanto antes.

**Comment by mariajoafana** [comment]
ya revisé: 
    contar-frecuencias.md  
    crear-y-ver-archivos-html-con-python.md  
    de-html-a-lista-de-palabras-1.md

**Comment by jairomelo** [comment]
@vgayolrs Me preparo entonces para la revisión desde el lunes 7/11 :wink:

**Comment by jairomelo** [comment]
@vgayolrs revisado todo el código de las lecciones, excepto por #11 todo funciona a la perfección 👍

**Comment by vgayolrs** [comment]
@mariajoafana , @jairomelo , @Alecitta: muchas gracias por sus indicaciones. Ya quedaron corregidas todas las lecciones de Python, texto y código. @jairomelo: como revisor externo dinos si el conjunto de lecciones está bien, con copia para Adam, para poderla pasar al repositorio definitivo. Una vez que lo hagas, me gustaría proponer que se incluya la mención a los revisores de traducciones en el bloque YAML.  Saludos!

**Comment by jairomelo** [comment]
@vgayolrs @mariajoafana Ya revisé el código y las lecciones. Por mi parte no he encontrado errores, los programas corren sin problemas y hay coherencia en el código entre una lección y otra (en particular el programa `obo.py` que estaba causando problemas). 

@acrymble, I checked the code for all the translations (#2) that the team did and all works fine. @vgayolrs added some notes to spanish words in at least one lesson (https://github.com/PH-espagnol/borradores/blob/master/lecciones/contar-frecuencias.md) where it is explained some tips about how to work with spanish text and special characters, also we made a list of stopwords in Spanish that could be usefull. I think everything is working well, both code as text translation.

Un saludo a todo el equipo, included @acrymble of course 😀

**Comment by vgayolrs** [comment]
cierro.
