### ISSUE TITLE
Correccion tres lecciones sobre manejo de datos 

### ISSUE THREAD

**Issue by vgayolrs** [PH-espagnol/borradores#12]
@mariajoafana @arojascastro : 

En el repositorio están tres lecciones interrelacionadas (de la sección original *Data Management*), que sería bueno revisar (errores de dedo, ortografía, redacción) antes de pedir la revisión externa.

https://github.com/PH-espagnol/borradores/blob/master/lecciones/preservar-datos-de-investigacion.md

https://github.com/PH-espagnol/borradores/blob/master/lecciones/introduccion-a-markdown.md

https://github.com/PH-espagnol/borradores/blob/master/lecciones/escritura-sustentable-usando-pandoc-y-markdown.md

Saludos!

**Comment by arojascastro** [comment]
Disculpa @vgayolrs @mariajoafana, quisiera revisar la leción sobre pandoc y me preguntaba si queréis que cree un "branch" propia y luego solicite una fusión, o bien pongo mis dudas en un "issue" (perdonad los anglicismos, debería intentar buscar el equivalente). Gracias.

**Comment by vgayolrs** [comment]
@arojascastro puedes marcar las correcciones directamente editado el original, con lo cual se creará automáticamente un "fork" en tu github. Si tienes alguna duda específica, la puedes poner en este hilo para no dispersar, indicando la línea o líneas en las que se encuentra la duda. Saludos!

**Comment by arojascastro** [comment]
Algunas dudas sobre la lección "Escritura sustentable usando Pandoc...". En concreto, no entiendo estas expresiones:
- Línea 59: "libre de desorden"
- Línea 259: `"Para citas entrecomilladas, pon la coma afuera de los signos de las comillas" [@nombre_título_fecha, 67].`
- Línea 320: "Para las autónomas"

No he revisado el original, así que no tengo como referencia lo que dice el autor; prefiero leer tu traducción y ver si "suena" bien y si no hay erratas. 

Ya he revisado la lección; en cuanto puedas, acepta los cambios que creas convenientes. 

Por cierto, ¿me podrías dar permiso para enviar los cambios desde mi repositorio local? Es posible que haya perdido el permiso porque borré el repositorio propio y luego lo volvía a clonar; ahora mismo, no puedo enviarlos... Gracias y disculpa.

**Comment by vgayolrs** [comment]
Mil gracias @arojascastro : esta tarde veo con atención tus dudas. Y sí, me parece buena idea no leer antes el original sino ver qué tanto se comprende la traducción. Sobre los permisos, déjame ver cómo resolverlo también esta tarde. Muchos saludos!

**Comment by arojascastro** [comment]
Comentarios a "Introducción a Markdown":
- La importación de la URL (https://raw.githubusercontent.com/es.programminghistorian/jekyll/gh-pages/lecciones/intro-a-bash.md) en Stackedit no funciona
- Hay que revisar los enlaces: `Para más tutoriales visita la página [Programming Historian en español] (es.programinghistorian.org "Programming Historian main page").`
- Creo que hay que traducir siempre _The Programming historian_ a _The programming historian en español_
- Faltan bastantes URL en los enlaces
- No entiendo esta expresión: 'Markdown es un término medio muy útil entre los archivos de texto plano sin estilo y los documentos de procesadores de texto heredados`. En concreto,`término medio` ¿?
  Además tengo algunas correcciones en mi repositorio local pero no puedo subirlas al repositorio remoto porque (creo) no tengo permiso. Cuando se solucione esto, sincronizo.

**Comment by arojascastro** [comment]
Ok, ya he conseguido hacer los dos "pull requests" que me faltaban... ahora solo hace falta que los apruebes :)

**Comment by vgayolrs** [comment]
@arojascastro ya revisé los permisos. En teoría deberías poder editar/escribir.

**Comment by arojascastro** [comment]
@vgayolrs sí, era un error mío, sorry.

**Comment by vgayolrs** [comment]
@arojascastro ya están aceptados los cambios de introducción a markdown, como podrás obervar. Del otro pull-request tengo una duda que te dejo marcada en comentario.
1) acerca de los enlaces: ninguno funciona hasta que no se decida la estrategia para el sitio web en español.
2) Sobre la frase: "'Markdown es un término medio muy útil entre los archivos de texto plano sin estilo y los documentos de procesadores de texto heredados", podría decir: "Markdown es muy útil ya que se sitúa en un término medio entre los archivos de.....".

Quedo pendiente de feedback.

**Comment by arojascastro** [comment]
@vgayolrs Sí, es mejor la alternativa que propones, la otra no la entendía.

**Comment by arojascastro** [comment]
Ya he revisado las tres lecciones. ¿Es suficiente o tenemos que encontrar un segundo revisor?

**Comment by vgayolrs** [comment]
@arojascastro Mil gracias. Estoy justo siguiendo tus correcciones. Ahora lo que necesitamos es el revisor externo. Si quieres preparo la solicitud para difundirla en la lista de correos que tiene @mariajoafana .

**Comment by arojascastro** [comment]
@vgayolrs creo que ya está solucionado el problema. ¿Puedes comprobarlo? ¿Cierro este issue?

**Comment by vgayolrs** [comment]
@arojascastro , parece que quedó bien. Ya lo cierro yo.

**Comment by arojascastro** [comment]
Las lecciones ya revisadas no se podrían publicar ya?

**Comment by vgayolrs** [comment]
@arojascastro depende del acuerdo al que se llegue según lo que se discuta acerca de la pertinencia del revisor de traducción externo para todas las traducciones o para las técnicamente difíciles.

**Comment by arojascastro** [comment]
@vgayolrs @mariajoafana al equipo inglés les pareció bien que revisaramos nosotros de momento hast enocontrar colaboradores externos; en mi opinión, si uno de nosotros traduce, los otros dos editores deben revisar. Qué os parece? @mariajoafana @vgayolrs

**Comment by vgayolrs** [comment]
De acuerdo. Para considerarlo en la lista de traducción y en los metadatos.

**Comment by vgayolrs** [comment]
@arojascastro @mariajoafana  entonces consideramos estas tres lecciones revisadas?

**Comment by arojascastro** [comment]
No sé si @mariajoafana las ha revisado también; en general creo que se necesitan dos revisores porque a mí seguro que se me escapó algo, pero como os guste.
