### ISSUE TITLE
Revisión "Introducción al control de versiones con GitHub Desktop"

### ISSUE THREAD

**Issue by arojascastro** [PH-espagnol/borradores#18]
Acabo de solicitar una fusión de mi repositorio con el de PHe. Veréis que he traducido la lección "Introducción al control de versiones con GitHub Desktop". Aunque aún tengo pendiente hacer la captura de pantallas, creo que ya se podría revisar desde un punto de vista lingüístico/estilístico. 

¿A quién le apetece revisarla?

**Comment by mariajoafana** [comment]
yo la reviso @arojascastro

**Comment by vgayolrs** [comment]
¿Les parece que lo subamos a borradores y se termine de editar ahí?

**Comment by arojascastro** [comment]
por mí sí, si es más fácil para todos, creo que con que aceptes el "merge" ya debería ponerse en "borradores"

**Comment by vgayolrs** [comment]
@arojascastro  Listo, y arreglado el bloque YAML.

**Comment by arojascastro** [comment]
@mariajoafana creo recordar que revisaste esta lección pero no encuentro tus comentarios en el archivo que hay en el repositorio. Me podrías recordar cómo acceder a ellos?

**Comment by mariajoafana** [comment]
Si @arojascastro yo la revisé pero ahora no la encuentro por ningún lado

**Comment by vgayolrs** [comment]
Le acabo de pegar una mirada rápida. Detecté que es necesario corregir enlaces a páginas de PH. Si lo puede hacer alguien, y cualquier otro detallito, serí abueno indicar el número de issue en la confirmació n de cambios (se verá reflejado en este ticket).

**Comment by arojascastro** [comment]
- ok, clicaré en los enlaces para ver si funcionan o no. Es eso a lo que te refieres no?
- acabo de subir las imágenes a la carpeta borradores/lecciones/imagenes/intro-github
- @vgayolrs te suena que ha podido pasar con la versión revisada por María?

**Comment by arojascastro** [comment]
@mariajoafana ya encontré tu revisión, estaba en la carpeta de borradores; los comentarios están en el mismo archivo. Creo que en adelante deberíamos comentar las sugerencias principales aquí como forma de "issue".
