### ISSUE TITLE
Revisión de tres lecciones

### ISSUE THREAD

**Issue by vgayolrs** [PH-espagnol/borradores#19]
@mariajoafana @arojascastro 
Están listas otras dos, agradeceré le echen un ojo:

https://github.com/PH-espagnol/borradores/blob/master/lecciones/introduccion-a-bash.md

https://github.com/PH-espagnol/borradores/blob/master/lecciones/instalar-modulos-python-pip.md

Saludos.

**Comment by arojascastro** [comment]
@mariajoafana @vgayolrs genial, me pongo con la de bash, que me interesa aprender :)

**Comment by arojascastro** [comment]
Por cierto, si revisamos lecciones no deberíamos estar también en el encabezado YAML?

**Comment by vgayolrs** [comment]
Buena idea @arojascastro ; habría que pensar (o buscar si ya se ha hecho), cómo etiquetar el metadato mada diferenciarlo de los "reviewers". Quizá con ponerlo en español..., pero no sé. Vamos preguntando en alguno de los correos de actualización de noviembre, ¿te parece?

**Comment by arojascastro** [comment]
Hola, @vgayolrs  y @mariajoafana, he revisado la introdución a Bash. Ya he pedido una fusión pero me gustaría comentar lo siguiente. 

Cambios:
- oprimir un botón --> pulsar un botón
- tolstoy --> tolstoi
- Enter --> Intro

Dudas:
- ¿basurero de reciclaje? ¿papelera?
- no entiendo por qué debería tener instalado ya "wget" (esto no es algo ortotipográfico, sino de contenido)
- en mi mac, mi carpeta raíz se llama usuarios/Antonio y no users/Antonio ... ¿no se traduce users?

Buena lección y traducción.

**Comment by vgayolrs** [comment]
@arojascastro casi inmediatamente que terminaste le di merge, muchas gracias.
Sobre las dudas:
- es un error, deberia ser "papelera de reciclaje" (recycling bin), pero se utiliza de ambas formas según la versión del OS X. Incluso para la versión en español de Sierra ahora cambió el nombre a "Basurero". Ya lo puse como 'papelera de reciclaje', a la antigua usanza de los anteriores OS X 10.x.
- Porque es posibe que hayas pasado por la lección sobre el uso de Wget y ya lo hayas descargado, o que ya lo tengas instalado por otra razón antes de leer esta lección.
- La pregunta se resuelve fácil: mira si en Terminal te muestra `users/Antonio` o `/usuarios/antonio` (cuando te localizas en el directorio de inicio en Terminal y le das `pwd` ¿qué te aparece?). Los nombres del sistema de archivos en línea de comandos siempre estarán en inglés (por lo tanto intraducible aunque tu sistema esté en español o en francés). En Finder seguramente sí te aparecerá con el nombre "Usuarios", de la misma manera que te aparecerá la carpeta "Escritorio" cuando estés en `home`, porque es una interfaz gráfica de usuario (GUI) e interpreta los nombres del sistema de archivos según el idioma que hayas determinado para la máquina; pero en Terminal y para efectos de uso de línea de comandos tendrás que escribir `desktop` en vez de `escritorio` y `users` en vez de `usuarios`, etc. También verás que en la pestaña de Terminal aparecen los nombres de los directorios en el idioma de uso (`usuarios` `escritorio`), porque es una GUI para trabajar en línea de comandos (en realidad es un simulador o emulador de las viejas interfaces). 

Quedo al pendiente de cualquier otro comentario. Saludos!

**Comment by arojascastro** [comment]
@vgayolrs tienes razón, lo probé en Terminal y sale Users y todo en inglés. En cuanto a la lección de wget, ¿no hay link o referencia? Se me hizo confuso porque no conocía esa lección... Por lo demás, todo muy bien :)

**Comment by vgayolrs** [comment]
@arojascastro listo! Incluí los enlaces completos a las lecciones en inglés de manera temporal.

**Comment by arojascastro** [comment]
esta lección no se podría publicar ya? en cualquier caso, puedo modificar los metadatos y ponerme como "translation proofreader"?

**Comment by arojascastro** [comment]
- ok, clicaré en los enlaces para ver si funcionan o no. Es eso a lo que te refieres no?
- acabo de subir las imágenes a la carpeta borradores/lecciones/imagenes/intro-github
- @vgayolrs te suena que ha podido pasar con la versión revisada por María?
