### ISSUE TITLE
Introducción a Python / Introduction to Python

### ISSUE THREAD

**Issue by vgayolrs** [PH-espagnol/borradores#2]
@arojascastro , @mariajoafana: Ya están terminados los borradores de las traducciones de la serie completa de lecciones sobre Python. Me parece que no tienen muchos problemas en cuanto a las explicaciones, aunque para asegurar que no haya dislates en los términos de informática, le he pedido a @alecitta (Alejandra Cárdenas, quien es informática), para que nos de su opinión (en ésta y cualquier otra traducción que implique términos de informática). Les ruego que lo revisen y hagan sus observaciones en el "branch" [comentarios](https://github.com/PH-espagnol/borradores/tree/comentarios), para corregirlas y pasarlas al repositorio [ph-submissions](https://github.com/programminghistorian/ph-submissions).

---

@acrymble : The whole Introduction to Python translation draft is done. I've translatede a few sentences within the code on lessons (comments, variables names, etc.) to make code more understandable to a Spanish reader. But I'm not shure 100% it's well done because I've only test about a 45% of it in my computer. So please, I would appreciate if you can check the code fragments on lessons in order to ensure there are no mistakes. Thanks a lot.

---

A continuación dejo un listado de la serie tal como debe ir

---

lista de archivos / file list
#### Introduction to Python / Introducción a Python

| English | Español |
| --- | --- |
| introduction-and-installation | [introduccion-e-instalacion](https://github.com/PH-espagnol/borradores/blob/master/lecciones/introduccion-e-instalacion.md) |
| mac-installation | [instalacion-mac](https://github.com/PH-espagnol/borradores/blob/master/lecciones/instalacion-mac.md) |
| linux-installation | [instalacion-linux](https://github.com/PH-espagnol/borradores/blob/master/lecciones/instalacion-linux.md) |
| windows-installation | [instalacion-windows](https://github.com/PH-espagnol/borradores/blob/master/lecciones/instalacion-windows.md) |
| viewing-html-files | [ver-archivos-html](https://github.com/PH-espagnol/borradores/blob/master/lecciones/ver-archivos-html.md) |
| working-with-text-files | [trabajar-con-archivos-de-texto](https://github.com/PH-espagnol/borradores/blob/master/lecciones/trabajar-con-archivos-de-texto.md) |
| code-reuse-and-modularity | [reutilizacion-de-codigo-y-modularidad](https://github.com/PH-espagnol/borradores/blob/master/lecciones/reutilizacion-de-codigo-y-modularidad.md) |
| working-with-web-pages | [trabajar-con-paginas-web](https://github.com/PH-espagnol/borradores/blob/master/lecciones/trabajar-con-paginas-web.md) |
| manipulating-strings-in-python | [manipular-cadenas-de-caracteres-en-python](https://github.com/PH-espagnol/borradores/blob/master/lecciones/manipular-cadenas-de-caracteres-en-python.md) |
| from-html-to-list-of-words-1 | [de-html-a-lista-de-palabras-1](https://github.com/PH-espagnol/borradores/blob/master/lecciones/de-html-a-lista-de-palabras-1.md) |
| from-html-to-list-of-words-2 | [de-html-a-lista-de-palabras-2](https://github.com/PH-espagnol/borradores/blob/master/lecciones/de-html-a-lista-de-palabras-2.md) |
| normalizing-data | [normalizar-datos](https://github.com/PH-espagnol/borradores/blob/master/lecciones/normalizar-datos.md) |
| counting-frequencies | [contar-frecuencias](https://github.com/PH-espagnol/borradores/blob/master/lecciones/contar-frecuencias.md) |
| creating-and-viewing-html-files-with-python | [crear-y-ver-archivos-html-con-python](https://github.com/PH-espagnol/borradores/blob/master/lecciones/crear-y-ver-archivos-html-con-python.md) |
| output-data-as-html-file | [salida-de-datos-como-archivo-html](https://github.com/PH-espagnol/borradores/blob/master/lecciones/salida-de-datos-como-archivo-html.md) |
| keywords-in-context-using-n-grams | [palabras-clave-en-contexto-n-grams](https://github.com/PH-espagnol/borradores/blob/master/lecciones/palabras-clave-en-contexto-n-grams.md) |
| output-keywords-in-context-in-html-file | [salida-palabras-clave-contexto-ngrams](https://github.com/PH-espagnol/borradores/blob/master/lecciones/salida-palabras-clave-contexto-ngrams.md) |

**Comment by acrymble** [comment]
Sure, I'll try to take a look. It's probably a good idea also to get
someone to test them out to make sure they work. This is what we use the
peer review process for.

Just a quick look at
https://github.com/PH-espagnol/borradores/blob/master/lecciones/de-html-a-lista-de-palabras-1.md

I notice you've translated some things but not others. For example:

# obo.py

def stripTags(contenidoPagina):
    startLoc = contenidoPagina.find("<p>")
    endLoc = contenidoPagina.rfind("<br/>")

```
contenidoPagina = contenidoPagina[startLoc:endLoc]
return contenidoPagina
```

stripTags, startLoc, and endLoc could all be translated if you wanted.

stripTags is shorthand for remove the HTML tags from the text

startLoc means the starting index position of the term we're looking for

endLoc means the ending index position of the term we're looking for.

If that's helpful I can help you try to identify those types of words
for you to translate. But if that's not what you're trying to do,
that's ok.

**Comment by vgayolrs** [comment]
That's a very good idea, @acrymble. Maybe @jairomelo could test the code. Anyway, I'll try it myself this week only to become more familar with Python and make sure it works (and translate such words that I was not sure if I was doing something wrong). Thanks for your helpful advice.

**Comment by jairomelo** [comment]
Perfectly @vgayolrs, I'm gonna test the code and check if there is any bug.

**Comment by mariajoafana** [comment]
@vgayolrs @arojascastro Estoy preparando unas notas sobre los avances del equipo editorial en español para la reunión del jueves.
En este link puede ver el google doc, editen según les parezca, no estoy segura de tener correcto el número de lecciones traducidas. [https://docs.google.com/a/neogranadina.org/document/d/1iuA7t9uF0GoKMWI14vNYrYyRRWb-rloKCvqUsiSxPoM/edit?usp=sharing](url)

**Comment by vgayolrs** [comment]
cierro
