### ISSUE TITLE
Revisión De la hermeneútica a las redes de datos: Extracción de datos y visualización de redes en fuentes históricas

### ISSUE THREAD

**Issue by mariajoafana** [PH-espagnol/borradores#21]
@arojascastro y @vgayolrs Por fin terminé la traducción de la lección sobre análisis de redes. También probé las tablas de atributos y relaciones de la lección con Palladio y todo funciona. Ya hice las capturas de las imágenes en Palladio con las tablas traducidas al español. ¿Saben dónde se suben las imágenes? Aun estoy trabajando en la traducción de las tablas de ejemplo que tiene la lección sobre el esquema de codificación.

Quería preguntarles si alguno tiene tiempo de hacerle edición. Otra opción podría ser enviar un llamado a las personas en nuestra base de datos a ver si alguien estaría interesado en colaborar como revisor y hacer el "proofreading".

**Comment by vgayolrs** [comment]
¡Excelente @mariajoafana  ! Cuenta conmigo para hacer una primera revisión, ya le he pegado una mirada diagonal y se ve muy bien. Para subir las imágenes voy a crear una carpeta y así nos permitirá probar cómo se insertan las imágenes en la lección. En cuanto la tenga lista te aviso para que las subas.

**Comment by vgayolrs** [comment]
@mariajoafana : puedes cargar tus imágenes de la lección en la siguiente carpeta:
https://github.com/PH-espagnol/borradores/tree/master/lecciones/imagenes/creando-diagramas-de-redes-desde-fuentes-historicas

**Comment by mariajoafana** [comment]
Buenísimo @vgayolrs muchas gracias!

**Comment by vgayolrs** [comment]
@mariajoafana perdón por la tardanza pero ya le di una primera pasada. Solamente dos dudas. 1) En la línea-57, ¿"hacer parte" o "formar parte"? Creo que podríamos llegar al acuerdo de utilizarlas indistintamente. 2) Línea-154: me resultó un poco confusa la traducción del paso no. 7. Después le doy otra pasada pero si puedes darte una vuelta por ese párrafo sería bueno.
Sobre las imágenes, veo que no cargaste ninguna al folder que abrimos.
Slds.

**Comment by mariajoafana** [comment]
Gracias @vgayolrs 
1) "Formar parte" parece mejor, lo cambié
2) Ya lo revisé y aclare la prosa del paso no.7
3) Acabo de cargar todas las imágenes y modifiqué el nombre de los archivos de imágenes en la lección para que sean los mismos que las imágenes que cargué.

**Comment by vgayolrs** [comment]
¡Genial!  Me parece que está bastante bien. ¿Discutieron el asunto de las revisiones de traducción en la reunión pasada?  ¿Sobre eso, qué procede para completar el flujo de trabajo?

**Comment by mariajoafana** [comment]
Si hablamos de eso. Para el equipo está bien que mientras arrancamos y formamos una base de colaboradores hagamos las revisiones entre nosotros. Yo propongo que esta lección la publiquemos un par de semanas después de lanzar la página con las lecciones de Python. Así cada cierto tiempo podemos circular en twitter las novedades en la página en español

**Comment by vgayolrs** [comment]
Ok, entonces para darle una segunda lectura más de edición de estilo para ponerla con las otras que ya están listas y pendientes en jekyll. También voy a ir modificando la lista de traducción de lecciones para consignar todos los cambios y ver cuáles ya se van a Jekyll.

**Comment by arojascastro** [comment]
Creo que también yo debería revisar la lección antes de que se publique. Pero hasta que no acabe con la traducción de la guía para autores no puedo. Mi traducción sobre GitHub fue revisada por María, @vgayolrs puedes revisarla tú también?

**Comment by vgayolrs** [comment]
@arojascastro #18
