### ISSUE TITLE
Revisión Página de Inicio

### ISSUE THREAD

**Issue by arojascastro** [PH-espagnol/borradores#27]
En la página de inicio (http://programminghistorian.org/es/), ¿sería posible corregir lo siguiente?

1. En el título, The Programming Historian en español --> *The  Programming Historian en español*
2. En "Si deseas ser un revisor o si tienes alguna sugerencia para hacer de Programming Historian en español un recurso más útil, por favor consulta nuestra página contribuciones." --> Si deseas ser un revisor o si tienes alguna sugerencia para hacer *The Programming Historian en español* un recurso más útil, por favor consulta nuestra página contribuciones.

**Comment by vgayolrs** [comment]
1) ¿Te refieres al título de la página ("Acerca de Programming Historian en español") o al del `header`?
2)  Ya está.

**Comment by arojascastro** [comment]
1. La que pone "Acerca de The Programming Historian en español", no sé si se puede poner en cursiva...

**Comment by vgayolrs** [comment]
No. Ese es un título generado desde el bloque YAML y no acepta formatos en segmentos (unas palabras en texto normal, otras en cursivas, por ejemplo) pues el metadato deja de funcionar y entonces marca error.

**Comment by arojascastro** [comment]
ok
