### ISSUE TITLE
Revisión de Índice de lecciones

### ISSUE THREAD

**Issue by arojascastro** [PH-espagnol/borradores#28]
En http://programminghistorian.org/es/lecciones/ ¿se puede cambiar lo siguiente?
1. Te envintamos  --> Te invitamos
2. Programming Historian --> *The Programming Historian*
3. sobretodo --> sobre todo
4. En los títulos de las lecciones: ambientes --> entornos (esto no sé si es incorrecto, quizás es en México se usa ambientes pero en España creo que es más común entornos, en tal caso, olvidadlo).

**Comment by vgayolrs** [comment]
1) ok
2) ok
3) ok
4) se utilizan ambos

**Comment by arojascastro** [comment]
Entiendo que al cerrar este issue, consideras que @mariajoafana no debe revisar, cierto?

**Comment by mariajoafana** [comment]
ya revisé, todo se ve bien ;)

**Comment by arojascastro** [comment]
Gracias! @mariajoafana 

Ha sido revisado por los tres.

Ok, entonces cierro.
