### ISSUE TITLE
Revisión Contribuye

### ISSUE THREAD

**Issue by arojascastro** [PH-espagnol/borradores#29]
Sugerencia de cambios:

1. En la sección "Traduce una lección" se podría poner enlace a la guía para autores http://programminghistorian.org/es/flujo-de-trabajo-nuevas-lecciones
2. En la sección "Conviérte en editor" a la guía que está siendo revisada en issue #25
3. El enlace en la sección "Envía tus comentarios" el enlace http://programminghistorian.org/es/comentarios lleva a 404  (hay que ver dónde está el archivo, el `slug`debe ser incorrecto)
 
Si no estoy equivocado, ¿alguien más puede revisar la lección y escribir los comentarios en este issue?

**Comment by vgayolrs** [comment]
1) ¿En qué segmento del texto quieres poner el enlace?
2) El enlace a la guia de editores ya está, falta colocar el archivo en jekyll/es/
3) corregido

**Comment by arojascastro** [comment]
Quizás en el segundo parrafo, poner algo así como: "Consulta nuestras instrucciones para autores" y el enlace: http://programminghistorian.org/es/flujo-de-trabajo-nuevas-lecciones 

Pero quizás hay que debatirlo con @mariajoafana

**Comment by arojascastro** [comment]
Cambio introducido por @vgayolrs en un commit que no he sabido localizar.
