### ISSUE TITLE
ver-archivos-html

### ISSUE THREAD

**Issue by jairomelo** [PH-espagnol/borradores#3]
1. En el código  que dice:

``` xml
<!doctype html>
<html dir="ltr" lang="es-ES">
    <meta http-equiv="Content-Type" content="text/htmal; charset=utf-8">

<head>
    <title><!-- Inserta aquí el título --></title>
</head>

<body>
    <!-- Inserta aquí el contenido -->
</body>
</html>
```

La línea 2 es incorrecta. Debe ser

``` html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
```

También, la declaración del código en Markdown dice `xml`¿no debería ser `html`?

2. En el último párrafo dice:

> Dependiendo de tu editor de texto puedes tener la opción `view page in brownser` u `open in brownser`.

Creo que la mayoría de máquinas ya están en español. Lo más seguro es que digan `Abrir como` y desplieguen una pestaña con los íconos de los _browsers_ (Fireworks, Chrome, IE, etc.)

**Comment by vgayolrs** [comment]
@jairomelo 
1)  línea 58 (la que denominas "2") corregida (gracias)
- sobre la declaración de código, así está en el _raw_ de la lección en inglés.

2) El editor de texto que uso (Komodo)  tiene todo el menú en inglés (imposible cambiarlo, no sé en el tuyo), e incluso no tiene manera de abrir el archivo HTML en el navegador, pero sí ofrece una vista previa en `view -> browser preview`.

Espero cualquier otra anotación antes de cerrar el tema. :)

**Comment by vgayolrs** [comment]
Código retificado.
