### ISSUE TITLE
Revisión de Equipo de proyecto

### ISSUE THREAD

**Issue by arojascastro** [PH-espagnol/borradores#30]
En http://programminghistorian.org/es/equipo-de-proyecto, sugerencias de cambio:
1. Ordenar los miembros alfabéticamente: yo debería ir detrás de Ian Milligan.
2. Falta punto y final en mi biografía.
3. Cambiar título/slug de Equipo de proyecto a Equipo (más corto y menos inglés, lo malo de esto son los enlaces: ¿vale la pena?)

Si no estoy equivocado, ¿alguien más puede revisar la lección y escribir los comentarios en este issue?

**Comment by vgayolrs** [comment]
1) Hecho. Pero hay que en el resto de PH. Si quieres me encargo.
2) Hecho
3) ¿sugerencias?

**Comment by arojascastro** [comment]
1. Lo acabo de proponer en el repositorio inglés, a ver qué dicen.
3. yo pondría es/equipo y en el menú igual Equipo

**Comment by arojascastro** [comment]
¿Qué os parece el cambio que sugería? Si no lo queremos hacer, ¿podemos cerrar esto? @vgayolrs @mariajoafana

**Comment by mariajoafana** [comment]
No había visto este issue. Me parece un buen cambio, aunque si se queda como está no me parece mal

**Comment by arojascastro** [comment]
Cierro esto y si acaso lo abrimos en /jekyll... yo sigo pensando que en el menú debiera leerse "Equipo" y "Acerca" en lugar de "Equipo de proyecto" y "Acerca de" . Qué pensáis @mariajoafana @vgayolrs?
