### ISSUE TITLE
Revisión Flujo de trabajo

### ISSUE THREAD

**Issue by arojascastro** [PH-espagnol/borradores#32]
No estoy seguro que esta página haya sido revisada: http://programminghistorian.org/es/flujo-de-trabajo-nuevas-lecciones

Si no estoy equivocado, ¿alguien más puede revisar la lección y escribir los comentarios en este issue?

**Comment by mariajoafana** [comment]
yo la reviso

**Comment by arojascastro** [comment]
Genial @mariajoafana! Por favor, escribe aquí las sugerencias de cambio o los errores que encuentres, así luego modificamos el archivo que está en Jekyll.

**Comment by mariajoafana** [comment]
Listo, algunas son sugerencias para clarificar o mejorar la prosa, en otras indico typos que necesitan corregirse. Déjame saber si todo está claro. 

Línea 19: Última frase sugiero modificar así para claridad: "También te asignaremos un editor para ayudarte a resolver dudas y a desarrollar la lección de la mejor manera."
Línea 21: Cambiar "¿Qué lección traducir?" por "¿Qué lecciones traducir? 
Añadir "el contexto de España y América Latina". 
*También hay que crear una página para las traducciones pendientes*
Línea 23: Sugiero cambiar la redacción un poco para claridad: "The Programming Historian en español no tiene un modelo de lección estándar. Recibimos lecciones sobre cualquier tema siempre y cuando ayuden a los humanistas (usualmente historiadores, pero no siempre) en cualquier fase del proceso de investigación y publicación.  
Línea 25: Arreglar vínculo de "lecciones ya publicadas".
Línea 31: cambiar "generla" por "general". Cambiar "mantener un recurso en abierto" por "mantener un recurso de acceso abierto". Cambiar "nuestrio" por "nuestro". Añadir "sitio" así: "transformarlos en un sitio web". 
Línea 33: Eliminar "a" antes de "seguir" en esta frase: "Esto implica que pidamos a los traductores y autores a seguir [tal vez adherirse quede mejor acá] una serie de requisitos".
Línea 39: Añadir: Puesto que nuestr[o] [sitio] web
Línea 56: última oración arreglar "entendder"
Línea 76: arreglar "sobratnes"
Línea 93: Arreglar en penúltima frase de párrafo: "... **negrita** o *cursiva* sin[o] con la anotación Markdow oportuna  
Línea 133: última oración: "otr[os] [sitios] web".
Línea 148: cambiar "tienen" por "tengan"
Línea 151: arreglar "Utiiza"
Línea 161: arregla "jemplo"
Linea 176: espacio de sobra: [versión en línea ]
Línea 216: Revisar primera oración pues no se entiende bien.
Línea 230: Revisar segunda oración desde "En cambio..."
Línea 245: cambiar "arrastra" por "arrastrar". Cambiar "clicar" por hacer clic. 
Línea 246: cambiar "han" por "hayan". Cambiar "Clica" por "Haz clic". Arreglar "quet". Cambiar "encuentra" por "encuentras". Arreglar "navegado". Arregla "arrastra" 
Línea 247: arreglar "visualiar"
Línea 248: arreglar "arvhicos" . Cambiar "pasamos" por "pasemos"
Línea 254: arreglar "envair"
Línea 256: arreglar "para tu"
Línea 259: arreglar "comletar". Lo de "en contra de nuestro deseo" suena un poco raro. Tal vez mejor "en ocasiones hay demoras y el proceso puede tomar más tiempo del que nos gustaría."
Línea 261: sugiero "revisión por pares abierta". Arreglar  "cóodo" 
Línea 269: arreglar "contact"

**Comment by arojascastro** [comment]
Ok, aquí van las mías:
1. [x] Antonio Rojas --> Anotnio Rojas Castro
2. [x] para en todo momento que --> para que en todo momento
3. [x] enlace a índice (http://programminghistorian.org/es/indice-de-lecciones) está roto, falta actualizar.
4. [x] lo generla --> lo general 
5. [x] a seguir --> seguir
6. [ ] sobra enlace en GitHub Pages (https://pages.github.com), 
7. [x] nuestro [equipo] (equipo-de-proyecto) --> falta enlace a http://programminghistorian.org/es/equipo-de-proyecto
8. [x] slug en cursiva
9. [x] encabezados contenidos en forma de bloque en los archivos de texto plano --> encabezados en forma de bloque en los archivos de texto plano
10. [x] copia y pega el texto situado más abajo al inicio de tu archivo de texto --> copia y pega al inicio de tu archivo de texto el texto situado más abajo 
11. [x] modificar bloque YAML para que aparezca traductor y "translation reviewer" o lo que acordamos.
12. [x] sobratnes  --> sobrantes
13. [x] Markdow es lenguaje de marcado --> es un lenguaje de marcado 
14. [x] [GitHub] (https://github.com/programminghistorian/ph-submissions/tree/gh-pages/lessons/spanish). --> error de marcado
15. [x] te ayduarán --> te ayudarán
16. [x] estrcutura --> estructura 
17. [x] sin con --> sino con 
18. [x] utilices # --> la almohadilla #33 
19. [x] traducción o traducción. --> traducción o lecció.
20. [x] scripts --> en cursiva 
21. [x] slug --> en cursiva 
22. [x] utiliar --> utilizar
23. [x] slug --> en cursiva
24. [x] Consulta una [ilustración de ejemplo] o bien la [versión en línea ]. --> falta insertar ejemplo
25. [x] Falta enlace en [sintaxis extendida] --> ???
26. [x] del nombre del código  --> y el nombre del código
27. [x] Puedes leer más sobre cómo [insertar código aquí]. --> arreglar esto
28. [x] teipo de comillas --> tipo de comillas
29. [x] prinicipo --> principio
30. [x]  Tenemos un Programming Historian project page en GitHub, donde mantemos dos repositorios (es decir, un sitio en donde almacenar archivos y carpetas). --> Tenemos un proyecto en GitHub, en donde mantenemos dos repositorios (es decir, un sitio en donde almacenar archivos y carpetas). [y poner enlace]
31. [x]  [web] (http://programminghistorian.org) --> poner enlace a la web española 
32. [x] nombre/slug --> nombre
33. [x] de manera --> quitar
34. [x] visita las --> consulta las 
35. [ ]  [carpeta de imágenes] (https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images) --> corregir enlace
36. [x] quet tiene --> que tiene 
37. [x] si no la encuentra --> si no la encuentras
38. [x] No puedes arrastra --> No puedes arrastrar
39. [x] visualiar tu lección --> visualizar tu lección
40. [x] los arvhicos --> los archivos
41. [x] el respositorio  --> el repositorio
42. [x] repositor Jekyll --> repositorio Jekyll
43. [x]  [guía para editores] (http://programminghistorian.org/editor-guidelines)  --> poner enlace
44. [x] resumimmos el proceso --> resumimos el proceso
45. [x]  cree una notificación de problema --> cree un *issue*
46. [x] comletar --> completar
47. [x] [puedes contactar con tu editor] (http://programminghistorian.org/project-team) --> poner enlace a la web en español
48. [x] nuestros comisarios Ian Milligan or Amanda Visconti. --> poner ombursperson en español
49. [x] contact con tu editor --> contact con tu editor
50. [x]  finilizado --> finalizado

**Comment by arojascastro** [comment]
Gracias @mariajoafana, intentaré corregir el texto esta semana.

**Comment by vgayolrs** [comment]
@arojascastro @mariajoafana yo hago la correcciones ahora que tengo tiempo.

**Comment by vgayolrs** [comment]
@mariajoafana todas tus correcciones integradas.
@arojascastro Hecho. Solamente algunos comentarios o dudas sobre:
1) ¿A qué te refieres con que sobra el enlace a Github Pages?
2) Sobre bloque YAML: dado que son instrucciones para lecciones (y traducciones), hice una versión para traducción. 
3) Sobre "nombre/slug" me pareció necesario aclarar que se trata del nombre del archivo, no de la lección.
4) Sobre el enlace a la carpeta de imágenes, sugiero dejarlo así por el momento porque hay que crear la carpeta en el repositorio que se decida usar.

**Comment by arojascastro** [comment]
1. @vgayolrs Me refería a esto: 

Utiliza un archivo de texto plano

Puesto que nuestro sitio web se publica mediante GitHub Pages (https://pages.github.com), las lecciones deben escribirse en texto plano, con el programa de edición que prefieras. 

El enlace está activado en GitHub Pages pero además hay entre paréntesis la URL; sobra, por tanto, la URL enter paréntesis... creo.

2. Genial.

3. Ok.

4. Ok.

**Comment by vgayolrs** [comment]
Era un problema de markdown que quedó arreglado hace rato.

**Comment by arojascastro** [comment]
Gracias @mariajoafana por la revisión y @vgayolrs por introducir los cambios. He mirado si os puedo poner como revisores pero no hay bloque YAML en esta página. Verdad?
