### ISSUE TITLE
Revisión Guía para revisores

### ISSUE THREAD

**Issue by arojascastro** [PH-espagnol/borradores#33]
Esta página (http://programminghistorian.org/es/guia-para-revisores) creo que tampoco ha sido revisada. A simple vista veo los siguientes errores:

1. [ ] En la seccion "Destinatario" hay un error de Markdown.
2. [ ] En la guía para editores escribí "política contra el acoso", aquí en cambio traduje o alguien tradjo Política antiacoso ¿qué os gusta más?
3. [ ] Creo que en la sección Cómo enviar tu revisión hay que poner el enlace a este repositorio. 

¿Alguien más puede revisar la lección y escribir los comentarios en este issue?

**Comment by vgayolrs** [comment]
Varios errores de md. Ya están corregidos. Por favor, si ves un error en Jekyll abre el ticket allá en PH y no en PH-espagnol para poder referirlo.

**Comment by arojascastro** [comment]
¿Pero está revisada esta página? Lo he abierto aquí para no molestar al resto.

**Comment by vgayolrs** [comment]
ok, yo lo hago ya que estoy en eso.

**Comment by arojascastro** [comment]
ok, ¿te parece bien que pongamos aquí los errores o los cambiamos directamente? @mariajoafana quieres/puedes revisar?

**Comment by mariajoafana** [comment]
estoy revisando

**Comment by arojascastro** [comment]
ok, por favor, comenta aquí los errores o lo que encuentres y cuando hayamos acabado, cerremos pero hasta entonces no. yo voy a revisar las instrucciones para autores ahora. creo que la que está peor es la guía para editores, porque he adaptado mucho el contenido @vgayolrs @mariajoafana

**Comment by arojascastro** [comment]
Hey @vgayolrs @mariajoafana esta página ha sido revisada y corregida? No localizo el issue o el commit... Se puede cerrar esto?

**Comment by mariajoafana** [comment]
Está corregida ya, se puede cerrar
