### ISSUE TITLE
trabajar-con-archivos-de-texto

### ISSUE THREAD

**Issue by jairomelo** [PH-espagnol/borradores#4]
1. En el código de `archivo-entrada.py` la variable _message_ puede ser traducida porque la declara el programador:

``` python
# archivo-entrada.py
f = open ('holamundo.txt', 'r')
mensaje = f.read()
print(mensaje)
f.close()
```

Ya lo probé y  funciona 😃 

2. El código en archivo-apendice.py no funciona. La sintaxis correcta es:

``` python
# archivo-apendice.py
f = open ('holamundo.txt','a')
f.write('\n' + 'Hola Mundo')
f.close()
```

**Comment by vgayolrs** [comment]
Corregido.
