### ISSUE TITLE
contar-frecuencias

### ISSUE THREAD

**Issue by jairomelo** [PH-espagnol/borradores#6]
No sé si será exagerar mucho, pero aquí se podría traducir el código así:

``` python

# count-list-items-1.py

cadenaPalabras = 'Desocupado lector: sin juramento me podr&aacute;s creer que quisiera este libro '
cadenaPalabras += 'como hijo del entendimiento fuera el m&aacute;s hermoso, el m&aacute;s gallardo y m&aacute;s discreto que pudiera imaginarse'

listaPalabras = cadenaPalabras.split()

frecuenciaPalab = []
for w in listaPalabras:
    frecuenciaPalab.append(listaPalabras.count(w))

print("Cadenas\n" + cadenaPalabras +"\n")
print("Lista\n" + str(listaPalabras) + "\n")
print("Frequencias\n" + str(frecuenciaPalab) + "\n")
print("Pares\n" + str(zip(listaPalabras, frecuenciaPalab)))

```

Se obtiene algo como esto

``` python

Cadenas
Desocupado lector: sin juramento me podr&aacute;s creer que quisiera este libro como hijo del entendimiento fuera el m&aacute;s hermoso, el m&aacute;s gallardo y m&aacute;s discreto que pudiera imaginarse

Lista
['Desocupado', 'lector:', 'sin', 'juramento', 'me', 'podr&aacute;s', 'creer', 'que', 'quisiera', 'este', 'libro', 'como', 'hijo', 'del', 'entendimiento', 'fuera', 'el', 'm&aacute;s', 'hermoso,', 'el', 'm&aacute;s', 'gallardo', 'y', 'm&aacute;s', 'discreto', 'que', 'pudiera', 'imaginarse']

Frequencias
[1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 2, 3, 1, 1, 3, 1, 2, 1, 1]

Pares
[('Desocupado', 1), ('lector:', 1), ('sin', 1), ('juramento', 1), ('me', 1), ('podr&aacute;s', 1), ('creer', 1), ('que', 2), ('quisiera', 1), ('este', 1), ('libro', 1), ('como', 1), ('hijo', 1), ('del', 1), ('entendimiento', 1), ('fuera', 1), ('el', 2), ('m&aacute;s', 3), ('hermoso,', 1), ('el', 2), ('m&aacute;s', 3), ('gallardo', 1), ('y', 1), ('m&aacute;s', 3), ('discreto', 1), ('que', 2), ('pudiera', 1), ('imaginarse', 1)]


```

La lista de comprensión también podría traducirse así

``` python
cadenaPalabras = 'Desocupado lector: sin juramento me podr&aacute;s creer que quisiera este libro '
cadenaPalabras += 'como hijo del entendimiento fuera el m&aacute;s hermoso, el m&aacute;s gallardo y m&aacute;s discreto que pudiera imaginarse'
listaPalabras = cadenaPalabras.split()

frecuenciaPalab = [listaPalabras.count(w) for w in listaPalabras]

print("Cadena\n" + cadenaPalabras +"\n")
print("Lista\n" + str(listaPalabras) + "\n")
print("Frequencias\n" + str(frecuenciaPalab) + "\n")
print("Pares\n" + str(zip(listaPalabras, frecuenciaPalab)))
```

También, no está incluido en las lecciones, pero se podría tener en cuenta que Python tiene problemas para interpretar cadenas de texto con símbolos. Por eso tuve que escribir las palabras acentuadas en HTML. 

@acrymble  I don't know if there is any place in the lessons where you explain about the use of special characters in text chains, by example "más", "cuánto". Python can't read it. It would be usefull in the spanish translation (maybe in HTML lessons) clarify the necessity to use HTML codes with special characters, by instance: "m&aacute;s", "cu&aacute;nto".

**Comment by acrymble** [comment]
Ya we don't have that problem in English. Good example of why direct
translation doesn't work for our needs. Same for variable names I presume?

**Comment by vgayolrs** [comment]
@jairomelo :  I found quite relevant your comment. That's one of the problems I saw when I tried the very first translation. But I have in mind that we have to adjust the other language translations to be the more similar to the English version in order to make it easy to track actualizations. Further, we have to think in a kind of _adennda_ to the original lessons to introduce those particularities, that could be useful when we come with the French or the Italian versión.  Working with strings in Spanish in Python, it will be an interesting challenge.

It's the same for variable names, @acrymble . But I assume that the Spanish readers (and code writers) will have no problems if there are no accent marks on variables names.

**Comment by jairomelo** [comment]
@vgayolrs @acrymble I found a symple solution. We just need to declare that we're working with utf-8 (just like in HTML):

``` python
# count-list-items-1.py
# -*- coding: utf-8 -*-

cadenaPalabras = 'Desocupado lector: sin juramento me podrás creer que quisiera este libro '
cadenaPalabras += 'como hijo del entendimiento fuera el más hermoso, el más gallardo y más discreto que pudiera imaginarse'
listaPalabras = cadenaPalabras.split()

frecuenciaPalab = [listaPalabras.count(w) for w in listaPalabras]

print("Cadena\n" + cadenaPalabras +"\n")
print("Lista\n" + str(listaPalabras) + "\n")
print("Frequencias\n" + str(frecuenciaPalab) + "\n")
print("Pares\n" + str(zip(listaPalabras, frecuenciaPalab)))
```

I test it and it works! 😄 (But not in variable names, although I think isn't necessary to use special characters in variable names)

**Comment by jairomelo** [comment]
#8 #9 #10

**Comment by vgayolrs** [comment]
@jairomelo : muchas gracias. Sigo con los arreglos a final de esta semana. No cerremos el tema mientras que no esté resuelto. Gracias.

**Comment by vgayolrs** [comment]
cierro
